stages:
  download_data:
    cmd: python scripts/download.py
    outs:
      - data/iris_dataset.csv
  process_data:
    cmd: python scripts/preproc_data.py
    deps:
      - data/iris_dataset.csv
      - scripts/prepro_data.py
    outs:
      - data/result_iris_dataset.csv