stages:
  download_data:
    cmd: python scr/download.py
    outs:
      - data/iris_dataset.csv
  process_data:
    cmd: python scr/preproc_data.py
    deps:
      - data/iris_dataset.csv
      - scr/preproc_data.py
    outs:
      - data/result_iris_dataset.csv