name: DVC CI

on:
  push:
    branches:
      - main

jobs:
  dvc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем полную историю для правильной работы DVC
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # Включаем кэширование pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir 'dvc[gdrive]'
          pip install --no-cache-dir gcloud

      - name: Configure DVC Remote
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: |
          mkdir -p .dvc/tmp
          echo "$GDRIVE_CREDENTIALS_DATA" > .dvc/tmp/credentials.json
          dvc remote remove gdrive || true
          dvc remote add -d gdrive gdrive://1hm66jFJqfauu2KmRa3gx43XVhRAVnBmq
          dvc remote modify gdrive --local gdrive_use_service_account true
          dvc remote modify gdrive --local gdrive_service_account_json_file_path .dvc/tmp/credentials.json

      - name: Pull DVC data
        run: |
          dvc status -v
          dvc remote list
          dvc pull -f -v || {
            echo "DVC pull failed"
            exit 1
          }
      
      - name: Run DVC Pipeline
        run: |
          dvc repro -v || {
            echo "DVC reproduction failed"
            exit 1
          }

      - name: DVC Push Data
        run: |
          dvc push -v || {
            echo "DVC push failed"
            exit 1
          }
      
      - name: Git Configuration
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Commit DVC changes
        run: |
          git add dvc.lock .dvc/config
          git commit -m "Update DVC configuration" || echo "No changes to commit"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update DVC tracking files [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          fi